import type { Locale } from "@/data/locales";
import { homeEs } from "@/data/translations";

export function CannabisExperience({ locale = "en" }: { locale?: Locale }) {
  const es = locale === "es-AR";
  const capabilities: { title: string; copy: string; tech: string; liveExample?: { name: string; label: string; url: string } }[] = [
    { title: "Native dispensary menus", copy: "Built a custom WordPress integration using the Dispense API to replace reverse-proxy-based dispensary menus with native, on-brand shopping experiences. The implementation supports products, carousels, navigation and customizable layouts directly inside WordPress and was designed for reuse across production sites.", tech: "Dispense API · WordPress · WooCommerce · PHP · JavaScript" },
    { title: "Dutchie Pro", copy: "Built WordPress themes and integrations using the Dutchie Pro SDK, including direct collaboration with Dutchie's engineering team when resolving implementation requirements.", tech: "Dutchie Pro SDK · WordPress · PHP · JavaScript", liveExample: { name: "The Fire Station — Hannahville", label: "View The Fire Station", url: "https://thefirestation.com/stores/hannahville" } },
    { title: "Store locators", copy: "Built custom WordPress store locator integrations using external cannabis retail data, including an implementation powered by Hoodie and a second variant using the Weedmaps Public API as its data source.", tech: "Hoodie API · Weedmaps API · WordPress · REST APIs" },
    { title: "Commerce and CRM integrations", copy: "Built and maintained integrations connecting WordPress and WooCommerce with external business systems including Salesforce, Authorize.net and Klaviyo.", tech: "Salesforce · WooCommerce · Authorize.net · Klaviyo · REST APIs" },
  ];
  return <section id="cannabis" className="section cannabis-section" aria-labelledby="cannabis-title"><div className="section-heading"><p className="section-label">{es ? homeEs.cannabisLabel : "Cannabis experience"}</p><h2 id="cannabis-title">{es ? homeEs.cannabisTitle : "Building inside the cannabis ecosystem, not around it."}</h2><p>{es ? homeEs.cannabisIntro : "At PufCreativ, I've spent over two years working on production websites and e-commerce systems for US cannabis brands and dispensaries. Much of that work involves connecting WordPress to the specialized platforms the industry relies on."}</p></div><div className="capabilities">{capabilities.map(({ title, copy, tech, liveExample }, index) => { const translated = homeEs.capabilities[index]; return <article className="capability" key={title}><h3>{es ? translated.title : title}</h3><p>{es ? translated.copy : copy}</p><p className="technology">{tech}</p>{liveExample && <><p>{es ? "Ejemplo en línea:" : "Live example:"} {liveExample.name}</p><a href={liveExample.url} target="_blank" rel="noopener noreferrer">{es ? translated.liveLabel : liveExample.label} <span aria-hidden="true">↗</span></a></>}</article>; })}<article className="capability"><h3>{es ? "Datos regulatorios del cannabis" : "Cannabis regulation data"}</h3><p>{es ? homeEs.capabilities[4].copy : "Worked on the interactive Hemp Beverage News regulation map, which allows users to explore cannabis and hemp beverage regulations across US states."}</p><a href="https://hempbeveragenews.com/regulations/" target="_blank" rel="noopener noreferrer">{es ? homeEs.capabilities[4].liveLabel : "View regulation map"} <span aria-hidden="true">↗</span></a></article></div></section>;
}
