export function CannabisExperience() {
  const capabilities = [
    ["Native dispensary menus", "Built a custom WordPress integration using the Dispense API to replace reverse-proxy-based dispensary menus with native, on-brand shopping experiences. The implementation supports products, carousels, navigation and customizable layouts directly inside WordPress and has replaced reverse-proxy dependencies across 5+ production sites.", "Dispense API · WordPress · WooCommerce · PHP · JavaScript"],
    ["Dutchie Pro", "Built WordPress themes and integrations using the Dutchie Pro SDK, including direct collaboration with Dutchie's engineering team when resolving implementation requirements.", "Dutchie Pro SDK · WordPress · PHP · JavaScript"],
    ["Store locators", "Built custom WordPress store locator integrations using external cannabis retail data, including an implementation powered by Hoodie and a second variant using the Weedmaps Public API as its data source.", "Hoodie API · Weedmaps API · WordPress · REST APIs"],
    ["Commerce and CRM integrations", "Built and maintained integrations connecting WordPress and WooCommerce with external business systems including Salesforce, Authorize.net and Klaviyo.", "Salesforce · WooCommerce · Authorize.net · Klaviyo · REST APIs"],
  ];
  return <section id="cannabis" className="section cannabis-section" aria-labelledby="cannabis-title"><div className="section-heading"><p className="section-label">Cannabis experience</p><h2 id="cannabis-title">Building inside the cannabis ecosystem, not around it.</h2><p>At PufCreativ, I&apos;ve spent the last 2.5 years working on production websites and e-commerce systems for US cannabis brands and dispensaries. Much of that work involves connecting WordPress to the specialized platforms the industry relies on.</p></div><div className="capabilities">{capabilities.map(([title, copy, tech]) => <article className="capability" key={title}><h3>{title}</h3><p>{copy}</p><p className="technology">{tech}</p></article>)}<article className="capability"><h3>Cannabis regulation data</h3><p>Worked on the interactive Hemp Beverage News regulation map, which allows users to explore cannabis and hemp beverage regulations across US states.</p><a href="https://hempbeveragenews.com/regulations/" target="_blank" rel="noopener noreferrer">View regulation map <span aria-hidden="true">↗</span></a></article></div></section>;
}
