import { caseStudyMedia, type CaseStudy } from "@/data/projects";
import { MetadataChips } from "@/components/metadata-chips";
import Image from "next/image";

export function CaseStudyPage({ caseStudy }: { caseStudy: CaseStudy }) {
  const projectHref = `/#${caseStudy.projectAnchorId}`;
  const media = caseStudyMedia[caseStudy.projectAnchorId];
  return <article className="detail-page"><a href={projectHref}>← Selected work</a><MetadataChips value={caseStudy.metadata} className="eyebrow case-study-meta" /><h1>{caseStudy.title}</h1><p className="case-study-intro">{caseStudy.intro}</p>{media && <figure className="case-study-media"><Image src={media.src} alt={media.alt} sizes="(max-width: 699px) calc(100vw - 32px), min(1040px, calc(100vw - 40px))" /><figcaption>{media.caption}</figcaption></figure>}{caseStudy.sections.map((section) => <section className="case-study-section" key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}{caseStudy.relatedPlatformExperience && <section className="case-study-section"><h2>Related platform experience</h2><p>{caseStudy.relatedPlatformExperience}</p></section>}{caseStudy.technologies && <section className="case-study-section"><h2>Technologies</h2><MetadataChips value={caseStudy.technologies} className="technology" /></section>}{caseStudy.liveProject && <section className="case-study-section"><h2>Live project</h2><p><a href={caseStudy.liveProject.url} target="_blank" rel="noopener noreferrer">{caseStudy.liveProject.label} <span aria-hidden="true">↗</span></a></p></section>}{caseStudy.liveExample && <section className="case-study-section"><h2>Live example</h2><p>{caseStudy.liveExample.description}</p><p><a href={caseStudy.liveExample.url} target="_blank" rel="noopener noreferrer">{caseStudy.liveExample.label} <span aria-hidden="true">↗</span></a></p></section>}<p className="case-study-back"><a href={projectHref}>← Back to selected work</a></p></article>;
}
